[package]
name = "reachability"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2021"
publish = false

[dependencies]
differential-dataflow = { path = "../../../differential-dataflow" }
dd_server = { path = "../../" }

[lib]
crate-type = ["dylib"]
