[package]
name = "dd_server"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition.workspace = true
publish = false

[dependencies]
libloading = "0.8"
differential-dataflow = { workspace = true }
timely = { workspace = true }
