[package]
name = "neighborhood"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition.workspace = true
publish = false

[dependencies]
differential-dataflow = { workspace = true }
dd_server = { path = "../../" }

[lib]
crate-type = ["dylib"]
